apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: gne0hy/curry:spring-4
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: test1234
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - port: 80
      targetPort: 8080
