pipeline {
    agent any

    environment {
        OS_AUTH_URL             = "http://10.242.0.50:5000/v3"
        OS_PROJECT_ID           = "aca5aa59b7264b2db407f58afac8667e"
        OS_PROJECT_NAME         = "curry"
        OS_USER_DOMAIN_NAME     = "Default"
        OS_PROJECT_DOMAIN_ID    = "default"
        OS_REGION_NAME          = "ap-northeast-2"
        OS_INTERFACE            = "public"
        OS_IDENTITY_API_VERSION = "3"
        TF_IN_AUTOMATION        = "true"
    }

    stages {
        stage('1. Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hoombahh/ktcloudinfraproj2.git'
            }
        }
// --- [1단계: 인프라 구축 (Terraform)] ---

        stage('2. 인증 파일 준비') {
            steps {
                script {
                    // 젠킨스 홈에 미리 넣어둔 clouds.yaml을 작업 폴더로 복사
                    sh 'cp /var/lib/jenkins/clouds.yaml ./openstack/'
                    // 잘 들어갔는지 확인
                    sh 'ls -l ./openstack/clouds.yaml'
                }
            }
        }

        stage('3. Terraform Init') {
            steps {
                dir('openstack') {
                    sh 'terraform init'
                }
            }
        }

        stage('4. Terraform Plan') {
            steps {
                dir('openstack') {
                    // 변경 사항 보여주기
                    sh 'terraform plan'
                }
            }
        }

        stage('5. Terraform Approval') {
            steps {
                input message: '테라폼 할거?'
            }
        }

        stage('6. Terraform Apply') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'os_auth_creds', passwordVariable: 'OS_PASSWORD', usernameVariable: 'OS_USERNAME')]) {
                    dir('openstack') {
                        // 진짜 생성
                        sh 'export OS_PASSWORD=\$OS_PASSWORD && terraform apply -auto-approve'
                        
                        // 나중을 위해 만들어진 IP를 파일로 저장
                        sh 'terraform output -raw master_ip > ../master_ip.txt'
                    }
                }
            }
        }
        
        stage('7. 접속 대기 (Wait for SSH)') {
            steps {
                script {
                    echo "VM 생성 완료, 30초 후 K8s 설치"
                    sleep 30
                }
            }
        }
        
// --- [2단계: 서비스 배포 (Kubernetes)] ---

        stage('8. 쿠버네티스 설치 (Install K8s)') {
            steps {
                script {
                    try {
                        def MASTER_IP = readFile('master_ip.txt').trim()
                        sshagent(credentials: ['ssh_key_openstack']) {
                            // 설치 스크립트 전송 및 실행
                            sh "scp -o StrictHostKeyChecking=no scripts/install_k8s.sh ubuntu@\${MASTER_IP}:/home/ubuntu/"
                            sh "ssh -o StrictHostKeyChecking=no ubuntu@\${MASTER_IP} 'bash /home/ubuntu/install_k8s.sh'"
                        }
                    } catch (Exception e) {
                        echo "에러"
                    }
                }
            }
        }
    }
}
